version: "3"

services:
    database:
        image: "postgres"
        environment:
            - POSTGRES_PASSWORD=postgrespassword
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        ports:
            - 5432:5432
        volumes:
            - /var/run/postgresql:/var/run/postgresql

    redis:
        image: "redis"
        expose:
            - "6379"
        ports:
            - "127.0.0.1:6379:6379"
